spring:
  graphql:
    graphiql:
      enabled: true
    schema:
      printer:
        enabled: true
  h2:
    console:
      path: "/h2-console"
      enabled: true
  datasource:
    url: "jdbc:h2:mem:testDB"
    username: bo
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create