spring:
  datasource:
    url: 'jdbc:h2:mem:testDB'
    username: 'bo'
  h2:
    console:
      enabled: true
      path: /h2-console

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.example.demo.article
